# Generated by Django 3.2 on 2022-10-02 09:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery/category_image/', verbose_name='Image')),
                ('slug', models.SlugField(default='Gallery-category-', unique=True, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Public date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(default='product-', unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='Gallery/images/', verbose_name='Image')),
                ('article', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Article')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub Category')),
                ('image', models.ImageField(upload_to='Gallery/subcategory_image/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', models.SlugField(default='Gallery-subcategory-', unique=True, verbose_name='URL')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Public date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImagesInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_images', models.ImageField(upload_to='Gallery/inline_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Gallery.images')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='Gallery.subcategory', verbose_name='SubCategory'),
        ),
    ]
